### ISSUE TITLE
gcc options craches binaries

### ISSUE THREAD

**Issue by d3vv** [serg-meus/k2#7]
crashed with mingw64 gcc after "uci" command

so as for me safest build with:

g++ main.cpp engine.cpp eval.cpp hash.cpp movegen.cpp chess.cpp Timer.cpp -std=c++0x -march=native -static -fno-exceptions -pipe -funroll-loops -ffunction-sections -Wl,--gc-sections -Wl,--strip-all -Wall -Wcast-qual -pedantic -Wextra -Wshadow -O3 -DNDEBUG=1 -o k2

but it produced warnings below:

main.cpp: In member function 'void k2main::SetboardCommand(std::__cxx11::string)':
main.cpp:267:44: warning: cast from type 'const char*' to type 'char*' casts away qualifiers [-Wcast-qual]
     if(!FenStringToEngine((char *)in.c_str()))
                                            ^
main.cpp: In member function 'void k2main::PerftCommand(std::__cxx11::string)':
main.cpp:298:11: warning: declaration of 'timer' shadows a member of 'k2main' [-Wshadow]
     Timer timer;
           ^~~~~
In file included from main.h:1:0,
                 from main.cpp:1:
engine.h:63:11: note: shadowed declaration is here
     Timer timer;
           ^~~~~
main.cpp: In member function 'void k2main::PositionCommand(std::__cxx11::string)':
main.cpp:661:55: warning: cast from type 'const char*' to type 'char*' casts away qualifiers [-Wcast-qual]
         if(!FenStringToEngine((char *)fenstring.c_str()))
                                                       ^
main.cpp: In member function 'void k2main::ProcessMoveSequence(std::__cxx11::string)':
main.cpp:695:47: warning: cast from type 'const char*' to type 'char*' casts away qualifiers [-Wcast-qual]
         if(!MakeMoveFinaly((char *)arg1.c_str()))
                                               ^
engine.cpp: In member function 'bool k2engine::MoveIsPseudoLegal(k2chess::move_c&, bool)':
engine.cpp:1571:67: warning: ?: using integer constants in boolean context [-Wint-in-bool-context]
         if(get_col(from_coord) != 4 || get_row(from_coord) != stm ? 0 : 7)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
eval.cpp: In member function 'k2chess::score_t k2eval::KingOpenFiles(k2chess::side_to_move_t)':
eval.cpp:1033:14: warning: declaration of 'k' shadows a previous local [-Wshadow]
         auto k = pawn_max[get_col(*rit)][king_color] ? 1 : 2;
              ^
eval.cpp:1002:10: note: shadowed declaration is here
     auto k = *king_coord[king_color];

**Comment by serg-meus** [comment]
I suppose, you forgot the -pthread option.

**Comment by d3vv** [comment]
-pthread not needed for msys2 mingw... in this case we used Windows threads, otherwise POSIX
but with -pthread binary crashed too with -flto:

$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-7.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 7.3.0 (Rev1, Built by MSYS2 project)

**Comment by serg-meus** [comment]
Hello!
Could you also add the '-g' option, compile, run and send me a [crash dump](https://helgeklein.com/support/creating-an-application-crash-dump/)?
P.S. Yes, there are many ugly things in the code. I'm a hobbyist developer so thank you for pointing them out.

**Comment by d3vv** [comment]
I've got it about hobby... But where i can get a dump(core-dump)?

dew@asus MINGW64 ~/k2
$ cat Makefile.FLTO
all:

        g++ -g main.cpp engine.cpp eval.cpp hash.cpp movegen.cpp chess.cpp Timer.cpp -std=c++0x -O3 -DNDEBUG=1 -pthread -o ./bin/Release/k2

dew@asus MINGW64 ~/k2
$ make -f Makefile.FLTO
g++ -g main.cpp engine.cpp eval.cpp hash.cpp movegen.cpp chess.cpp Timer.cpp -std=c++0x -O3 -DNDEBUG=1 -pthread -o ./bin/Release/k2

dew@asus MINGW64 ~/k2
$ ./k2.exe
uci
Segmentation fault

**Comment by d3vv** [comment]
sorry about previous post

**Comment by d3vv** [comment]
dew@asus MINGW64 ~/k2
$ cat Makefile.FLTO
all:

        g++ -g -flto -static main.cpp engine.cpp eval.cpp hash.cpp movegen.cpp chess.cpp Timer.cpp -std=c++0x -O3 -DNDEBUG=1 -pthread -o ./bin/Release/k2

dew@asus MINGW64 ~/k2
$ make -f Makefile.FLTO
g++ -g -flto -static main.cpp engine.cpp eval.cpp hash.cpp movegen.cpp chess.cpp Timer.cpp -std=c++0x -O3 -DNDEBUG=1 -pthread -o ./bin/Release/k2

dew@asus MINGW64 ~/k2
$ bin/Release/k2.exe
uci
Segmentation fault

dew@asus MINGW64 ~/k2

There is a problem with -static + -flto options

**Comment by d3vv** [comment]
[k2.exe.15136.zip](https://github.com/serg-meus/k2/files/1773159/k2.exe.15136.zip)

**Comment by d3vv** [comment]
[k2.exe.12116.zip](https://github.com/serg-meus/k2/files/1773163/k2.exe.12116.zip)

**Comment by d3vv** [comment]
crush dumps above from %LOCALAPPDATA%\CrashDumps

**Comment by serg-meus** [comment]
Can't reproduce the issue
