### ISSUE TITLE
Go searchmoves

### ISSUE THREAD

**Issue by LocutusOfPenguin** [serg-meus/k2#9]
Hi Sergey,

we had something similar on https://github.com/serg-meus/k2/issues/1#issuecomment-229731469
Can y consider to support this (by uci docu needed) feature, please?

Jürgen

**Comment by LocutusOfPenguin** [comment]
uciok
go movetime 10 searchmoves h2h3 h2h4
info depth 1 score cp 6 time 0 nodes 1 pv h2h3 
info depth 1 score cp 7 upperbound time 0 nodes 2 pv h2h4 
info depth 1 score cp 7 time 0 nodes 2 pv h2h4 
info depth 2 score cp -40 lowerbound time 0 nodes 4 pv h2h4 
info depth 2 score cp -50 time 0 nodes 27 pv h2h4 b8c6 
bestmove h2h4 ponder b8c6

go movetime 10 searchmoves c2c3
info depth 1 score cp -50 lowerbound time 0 nodes 1 pv h2h3 
info depth 1 score cp -38 upperbound time 0 nodes 3 pv c2c3 
info depth 1 score cp -19 time 0 nodes 3 pv c2c3 
info depth 2 score cp -66 lowerbound time 0 nodes 5 pv c2c3 
info depth 2 score cp -65 upperbound time 0 nodes 13 pv h2h3 
info depth 2 score cp -52 time 0 nodes 33 pv h2h3 b8c6 
info depth 2 score cp -50 upperbound time 0 nodes 34 pv h2h4 
info depth 2 score cp -50 time 0 nodes 34 pv h2h4 b8c6 
bestmove h2h4 ponder b8c6


go movetime 10
info depth 1 score cp 8 time 0 nodes 1 pv b1c3 
info depth 2 score cp 8 time 0 nodes 21 pv b1c3 
bestmove b1c3 ponder b8c6
go movetime 10 searchmoves h2h3
info depth 1 score cp 6 time 0 nodes 1 pv h2h3 
info depth 2 score cp -41 lowerbound time 0 nodes 3 pv h2h3 
info depth 2 score cp -52 time 0 nodes 24 pv h2h3 b8c6 
bestmove h2h3 ponder b8c6
go movetime 10      
info depth 1 score cp -52 lowerbound time 0 nodes 1 pv h2h3 
info depth 1 score cp -52 time 0 nodes 2 pv h2h3 
info depth 2 score cp -52 time 0 nodes 3 pv h2h3 
bestmove h2h3 ponder b8c6


Hi, thanks so far!
But it seems to not fully working.
If i give another searchmoves the old values should be overridden. And if no searchmoves (or maybe invalid?) the full moves restored.
See above.

**Comment by LocutusOfPenguin** [comment]
great. Works. Thanks!

**Comment by serg-meus** [comment]
Thank you, Jürgen
